name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  go_build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go build -v .
  go_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go test ./... -timeout 1m
  go_acceptance_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - 0.12.31
          - 0.13.7
          - 0.14.11
          - 0.15.5
          - 1.0.11
          - 1.1.2
    steps:
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - run: go mod download
      - name: Start Mattermost instance
        run: docker compose up --wait
      - name: Create Mattermost admin user
        run: docker compose exec mattermost mmctl --local user create
          --email admin@example.com
          --username admin
          --password admin
          --disable-welcome-email
      - env:
          TF_ACC: 1
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
          MM_URL: http://localhost:8065
          MM_LOGIN_ID: admin
          MM_PASSWORD: admin
        run: go test ./... -v -timeout 5m
  go_generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1.4.0
      - run: go generate
      - name: Check for Git differences
        run: git diff --compact-summary --exit-code
